/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    sys_conf.h
  * @author  MCD Application Team
  * @brief   Applicative configuration, e.g. : debug, trace, low power, sensors
  ******************************************************************************
  * @attention
  *
  * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
  * All rights reserved.</center></h2>
  *
  * This software component is licensed by ST under Ultimate Liberty license
  * SLA0044, the "License"; You may not use this file except in compliance with
  * the License. You may obtain a copy of the License at:
  *                             www.st.com/SLA0044
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __SYS_CONF_H__
#define __SYS_CONF_H__

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
/* USER CODE BEGIN Includes */

/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
/* USER CODE BEGIN ET */

/* USER CODE END ET */

/* Exported constants --------------------------------------------------------*/

/**
  * @brief Temperature and pressure values are retrieved from sensors shield
  *        (instead of sending dummy values). It requires MEMS IKS shield
  */
#define SENSOR_ENABLED              0

/**
  * @brief  Verbose level for all trace logs
  */
#define VERBOSE_LEVEL               VLEVEL_M

/**
  * @brief Enable trace logs
  */
#define APP_LOG_ENABLED             0

/**
  * @brief Enable MCU Debugger pins (dbg serial wires, sbg spi, etc)
  */
#define DEBUGGER_ENABLED            0

/**
  * @brief Enable four wires usable as probes (two of them PROBE1 and PROBE2 used by the MW)
  */
#define PROBE_PINS_ENABLED          0

/**
  * @brief Disable Low Power mode
  * @note  0: LowPowerMode enabled. MCU enters stop2 mode, 1: LowPowerMode disabled. MCU enters sleep mode only
  */
#define LOW_POWER_DISABLE           0

/**
  * @brief Keep LED on whenever MCU is awake, and off while in STOP2
  * @note  1: enabled, 0: disabled
  */
#define LPM_AWAKE_LED_ENABLED       1

/**
  * @brief Enable TX/RX LED blink timers (wakes MCU from STOP2 for each blink)
  * @note  1: enabled, 0: disabled – disable to avoid unnecessary wakeups
  */
#define TX_RX_LED_ENABLED           0

/* USER CODE BEGIN EC */

/* SCD41 sensor support -----------------------------------------------------*/
#define SCD41_ENABLED                      1

/* I2C2 bus configuration is generated by CubeMX in Core/Src/i2c.c */
#define SCD41_I2C_TIMEOUT_MS               100U

/* Single-shot timing from SCD41 datasheet */
#define SCD41_WAKEUP_DELAY_MS              30U
#define SCD41_SINGLE_SHOT_WAIT_MS          5000U
#define SCD41_SINGLE_SHOT_RHT_WAIT_MS      50U

/* SCD41 runtime configuration */
#define SCD41_TEMPERATURE_OFFSET_C_X100    0U
#define SCD41_SENSOR_ALTITUDE_M            0U
#define SCD41_AMBIENT_PRESSURE_MBAR        0U
#define SCD41_ASC_ENABLED                  0U
#define SCD41_PERSIST_SETTINGS             0U

/* LC709203F battery monitor support --------------------------------------*/
#define LC709203F_ENABLED                  1
#define LC709203F_I2C_TIMEOUT_MS           100U
#define LC709203F_WAKEUP_DELAY_MS          3U
#define LC709203F_VOLTAGE_MIN_MV           2600U
#define LC709203F_VOLTAGE_MAX_MV           4500U

/* USER CODE END EC */

/* External variables --------------------------------------------------------*/
/* USER CODE BEGIN EV */

/* USER CODE END EV */

/* Exported macro ------------------------------------------------------------*/
/* USER CODE BEGIN EM */

/* USER CODE END EM */

/* Exported functions prototypes ---------------------------------------------*/
/* USER CODE BEGIN EFP */

/* USER CODE END EFP */

#ifdef __cplusplus
}
#endif

#endif /* __SYS_CONF_H__ */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
