name: Build

on:
  pull_request:
    branches: [main]
    paths:
      - software/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: software
    steps:
      - uses: actions/checkout@v4

      - name: Install ARM GCC toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Build
        run: make build

